### ISSUE TITLE
Setup Continuous Integration

### ISSUE THREAD

**Issue by jarrettHoltz** [ut-amrl/ut_multirobot_sim#3]
Continuous Integration, primarily aimed at monitoring and testing the main branch as opposed to development branches.

**Comment by kylevedder** [comment]
I have a [.travis.yml](https://github.com/kylevedder/ServiceRobotControlStack/blob/master/.travis.yml) file that automatically sets up and installs ROS melodic on an Ubuntu 18.04 VM. You will only need to change a few of the `install` target lines because you're not using `catking_make`, and you will need to update the `script` target to actually do the testing you want to do. I suggest modifying [my python script](https://github.com/kylevedder/ServiceRobotControlStack/blob/master/ci/ci_tasks.py) which wraps and rigs up all the commands you want to run, [as it makes reading and modifying it later much easier](https://github.com/kylevedder/ServiceRobotControlStack/blob/master/ci/ci_tasks.py#L81). If you want any help getting this rigged up, message me; I'd do it myself, but I think it would be better if the build was owned by someone at UT.

**Comment by kylevedder** [comment]
This should be pushed up the stack. The code that sits on master does not build without special configuration as the default C++ compiler, `g++`, does not support the `-Qunused-arguments` (this is [`clang` specific](https://clang.llvm.org/docs/ClangCommandLineReference.html)).

**Comment by jarrettHoltz** [comment]
We have an initial CI system up and running now. This currently just builds the repo in clang and gcc, as of now there are no tests or integrations running. Adding those things is a separate issue.
